abbrev = {
    "$" : " dollar ",
    "€" : " euro ",
    "4ao" : "for adults only",
    "a.m" : "before midday",
    "a3" : "anytime anywhere anyplace",
    "aamof" : "as a matter of fact",
    "acct" : "account",
    "adih" : "another day in hell",
    "afaic" : "as far as i am concerned",
    "afaict" : "as far as i can tell",
    "afaik" : "as far as i know",
    "afair" : "as far as i remember",
    "afk" : "away from keyboard",
    "app" : "application",
    "approx" : "approximately",
    "apps" : "applications",
    "asap" : "as soon as possible",
    "asl" : "age, sex, location",
    "atk" : "at the keyboard",
    "ave." : "avenue",
    "aymm" : "are you my mother",
    "ayor" : "at your own risk", 
    "b&b" : "bed and breakfast",
    "b+b" : "bed and breakfast",
    "b.c" : "before christ",
    "b2b" : "business to business",
    "b2c" : "business to customer",
    "b4" : "before",
    "b4n" : "bye for now",
    "b@u" : "back at you",
    "bae" : "before anyone else",
    "bak" : "back at keyboard",
    "bbbg" : "bye bye be good",
    "bbc" : "british broadcasting corporation",
    "bbias" : "be back in a second",
    "bbl" : "be back later",
    "bbs" : "be back soon",
    "be4" : "before",
    "bfn" : "bye for now",
    "blvd" : "boulevard",
    "bout" : "about",
    "brb" : "be right back",
    "bros" : "brothers",
    "brt" : "be right there",
    "bsaaw" : "big smile and a wink",
    "btw" : "by the way",
    "bwl" : "bursting with laughter",
    "c/o" : "care of",
    "cet" : "central european time",
    "cf" : "compare",
    "cia" : "central intelligence agency",
    "csl" : "can not stop laughing",
    "cu" : "see you",
    "cul8r" : "see you later",
    "cv" : "curriculum vitae",
    "cwot" : "complete waste of time",
    "cya" : "see you",
    "cyt" : "see you tomorrow",
    "dae" : "does anyone else",
    "dbmib" : "do not bother me i am busy",
    "diy" : "do it yourself",
    "dm" : "direct message",
    "dwh" : "during work hours",
    "e123" : "easy as one two three",
    "eet" : "eastern european time",
    "eg" : "example",
    "embm" : "early morning business meeting",
    "encl" : "enclosed",
    "encl." : "enclosed",
    "etc" : "and so on",
    "faq" : "frequently asked questions",
    "fawc" : "for anyone who cares",
    "fb" : "facebook",
    "fc" : "fingers crossed",
    "fig" : "figure",
    "fimh" : "forever in my heart", 
    "ft." : "feet",
    "ft" : "featuring",
    "ftl" : "for the loss",
    "ftw" : "for the win",
    "fwiw" : "for what it is worth",
    "fyi" : "for your information",
    "g9" : "genius",
    "gahoy" : "get a hold of yourself",
    "gal" : "get a life",
    "gcse" : "general certificate of secondary education",
    "gfn" : "gone for now",
    "gg" : "good game",
    "gl" : "good luck",
    "glhf" : "good luck have fun",
    "gmt" : "greenwich mean time",
    "gmta" : "great minds think alike",
    "gn" : "good night",
    "g.o.a.t" : "greatest of all time",
    "goat" : "greatest of all time",
    "goi" : "get over it",
    "gps" : "global positioning system",
    "gr8" : "great",
    "gratz" : "congratulations",
    "gyal" : "girl",
    "h&c" : "hot and cold",
    "hp" : "horsepower",
    "hr" : "hour",
    "hrh" : "his royal highness",
    "ht" : "height",
    "ibrb" : "i will be right back",
    "ic" : "i see",
    "icq" : "i seek you",
    "icymi" : "in case you missed it",
    "idc" : "i do not care",
    "idgadf" : "i do not give a damn fuck",
    "idgaf" : "i do not give a fuck",
    "idk" : "i do not know",
    "ie" : "that is",
    "i.e" : "that is",
    "ifyp" : "i feel your pain",
    "IG" : "instagram",
    "iirc" : "if i remember correctly",
    "ilu" : "i love you",
    "ily" : "i love you",
    "imho" : "in my humble opinion",
    "imo" : "in my opinion",
    "imu" : "i miss you",
    "iow" : "in other words",
    "irl" : "in real life",
    "j4f" : "just for fun",
    "jic" : "just in case",
    "jk" : "just kidding",
    "jsyk" : "just so you know",
    "l8r" : "later",
    "lb" : "pound",
    "lbs" : "pounds",
    "ldr" : "long distance relationship",
    "lmao" : "laugh my ass off",
    "lmfao" : "laugh my fucking ass off",
    "lol" : "laughing out loud",
    "ltd" : "limited",
    "ltns" : "long time no see",
    "m8" : "mate",
    "mf" : "motherfucker",
    "mfs" : "motherfuckers",
    "mfw" : "my face when",
    "mofo" : "motherfucker",
    "mph" : "miles per hour",
    "mr" : "mister",
    "mrw" : "my reaction when",
    "ms" : "miss",
    "mte" : "my thoughts exactly",
    "nagi" : "not a good idea",
    "nbc" : "national broadcasting company",
    "nbd" : "not big deal",
    "nfs" : "not for sale",
    "ngl" : "not going to lie",
    "nhs" : "national health service",
    "nrn" : "no reply necessary",
    "nsfl" : "not safe for life",
    "nsfw" : "not safe for work",
    "nth" : "nice to have",
    "nvr" : "never",
    "nyc" : "new york city",
    "oc" : "original content",
    "og" : "original",
    "ohp" : "overhead projector",
    "oic" : "oh i see",
    "omdb" : "over my dead body",
    "omg" : "oh my god",
    "omw" : "on my way",
    "p.a" : "per annum",
    "p.m" : "after midday",
    "pm" : "prime minister",
    "poc" : "people of color",
    "pov" : "point of view",
    "pp" : "pages",
    "ppl" : "people",
    "prw" : "parents are watching",
    "ps" : "postscript",
    "pt" : "point",
    "ptb" : "please text back",
    "pto" : "please turn over",
    "qpsa" : "what happens", #"que pasa",
    "ratchet" : "rude",
    "rbtl" : "read between the lines",
    "rlrt" : "real life retweet", 
    "rofl" : "rolling on the floor laughing",
    "roflol" : "rolling on the floor laughing out loud",
    "rotflmao" : "rolling on the floor laughing my ass off",
    "rt" : "retweet",
    "ruok" : "are you ok",
    "sfw" : "safe for work",
    "sk8" : "skate",
    "smh" : "shake my head",
    "sq" : "square",
    "srsly" : "seriously", 
    "ssdd" : "same stuff different day",
    "tbh" : "to be honest",
    "tbs" : "tablespooful",
    "tbsp" : "tablespooful",
    "tfw" : "that feeling when",
    "thks" : "thank you",
    "tho" : "though",
    "thx" : "thank you",
    "tia" : "thanks in advance",
    "til" : "today i learned",
    "tl;dr" : "too long i did not read",
    "tldr" : "too long i did not read",
    "tmb" : "tweet me back",
    "tntl" : "trying not to laugh",
    "ttyl" : "talk to you later",
    "u" : "you",
    "u2" : "you too",
    "u4e" : "yours for ever",
    "utc" : "coordinated universal time",
    "w/" : "with",
    "w/o" : "without",
    "w8" : "wait",
    "wassup" : "what is up",
    "wb" : "welcome back",
    "wtf" : "what the fuck",
    "wtg" : "way to go",
    "wtpa" : "where the party at",
    "wuf" : "where are you from",
    "wuzup" : "what is up",
    "wywh" : "wish you were here",
    "yd" : "yard",
    "ygtr" : "you got that right",
    "ynk" : "you never know",
    "zzz" : "sleeping bored and tired"
}

emoji_dict = {
    "😀": "positive",
    "😃": "positive",
    "😄": "positive",
    "😁": "positive",
    "😆": "positive",
    "😊": "positive",
    "😍": "positive",
    "😘": "positive",
    "😜": "positive",
    "😝": "positive",
    "😛": "positive",
    "😊": "positive",
    "😂": "positive",
    "🤣": "positive",
    "😌": "positive",
    "😇": "positive",
    "😉": "positive",
    "😎": "positive",
    "😋": "positive",
    "🙂": "positive",
    "🤩": "positive",
    "🥳": "positive",
    "👍": "positive",
    "🙌": "positive",
    "👏": "positive",
    "🔥": "positive",
    "💯": "positive",
    "❤️": "positive",
    "💕": "positive",
    "💞": "positive",
    "💖": "positive",
    "💗": "positive",
    "💓": "positive",
    "💘": "positive",
    "💝": "positive",
    "🤗": "positive",
    "🤭": "positive",
    "🤦": "negative",
    "🤦‍♂️": "negative",
    "🤦‍♀️": "negative",
    "🙅": "negative",
    "🙅‍♂️": "negative",
    "🙅‍♀️": "negative",
    "🙍": "negative",
    "🙍‍♂️": "negative",
    "🙍‍♀️": "negative",
    "🤢": "negative",
    "🤮": "negative",
    "🤕": "negative",
    "👎": "negative",
    "👊": "negative",
    "💔": "negative",
    "💩": "negative",
    "😔": "negative",
    "😞": "negative",
    "😟": "negative",
    "😢": "negative",
    "😭": "negative",
    "😩": "negative",
    "😫": "negative",
    "😖": "negative",
    "😕": "negative",
    "😤": "negative",
    "😠": "negative",
    "😡": "negative",
    "👿": "negative",
    "😾": "negative",
    "😿": "negative",
    "😕": "negative",
    "🙁": "negative",
    "😞": "negative",
    "😠": "negative",
    "😒": "negative",
    "😔": "negative",
    "🙀": "negative",
    "🤬": "negative",
    "😐": "neutral",
    "😑": "neutral",
    "😶": "neutral",
    "🤨": "neutral",
    "🤷": "neutral",
    "🤷‍♂️": "neutral",
    "🤷‍♀️": "neutral",
}

emoticons = {
    r"#(": "negative",
    r"#-(": "negative",
    r"#)": "positive",
    r"#-)": "positive",
    r"#.#": "negative",
    r"#:0": "negative",
    r"#:-0": "negative",
    r"#:o": "negative",
    r"#:O": "negative",
    r"#:-o": "negative",
    r"#:-O": "negative",
    r"#_#": "negative",
    r"%(": "negative",
    r"%-(": "negative",
    r"%)": "positive",
    r"%-)": "positive",
    r"( ^)o(^ )": "positive",
    r"（　´∀｀）": "positive",
    r"( ・ω・)": "positive",
    r"( 一一)": "negative",
    r"(#.#)": "negative",
    r"(#^.^#)": "positive",
    r"(#_#)": "negative",
    r"((+_+))": "negative",
    r"(゜-゜)": "negative",
    r"(゜゜)": "negative",
    r"(*^。^*)": "positive",
    r"(*^^)v": "positive",
    r"(-=": "positive",
    r"(=<": "negative",
    r"(-=<": "negative",
    r"（⌒▽⌒）": "positive",
    r"（●＾o＾●）": "positive",
    r"(・。・;": "negative",
    r"(・_・;)": "negative",
    r"（・∀・）": "positive",
    r"(・・;)": "negative",
    r"(・・?": "neutral",
    r"(・へ・)": "negative",
    r"(8": "positive",
    r"(-8": "positive",
    r"(k)": "positive",
    r"(K)": "positive",
    r"(l)": "positive",
    r"(L)": "positive",
    r"(n_n)": "positive",
    r"(N_N)": "positive",
    r"(nn)": "positive",
    r"(NN)": "positive",
    r"(゜o゜)": "positive",
    r"(o:": "positive",
    r"(o;": "neutral",
    r"(T_T)": "negative",
    r"(Ｔ▽Ｔ)": "negative",
    r"(ToT)": "negative",
    r"(U)": "negative",
    r"(u)": "negative",
    r"(゜レ゜)": "negative",
    r"(ー_ー)!!": "negative",
    r"(ーー゛)": "negative",
    r"(ーー;)": "negative",
    r"（*^_^*）": "positive",
    r"(*^_^*;)": "neutral",
    r"(*^▽^*)": "positive",
    r"(*^0^*)": "positive",
    r"(*_*)": "negative",
    r"(*_*;": "negative",
    r"(-.-)": "negative",
    r"(゜.゜)": "negative",
    r"(/_;)": "negative",
    r"(:": "positive",
    r"(-:": "positive",
    r"(:_;)": "negative",
    r"(';')": "neutral",
    r"(;_:)": "negative",
    r"(;_;": "negative",
    r"(;_;)": "negative",
    r"(;O;)": "negative",
    r"(；一_一)": "negative",
    r"(?_?)": "negative",
    r"(@_@)": "negative",
    r"(@_@。": "negative",
    r"(＠_＠;)": "negative",
    r"(^ ^)": "positive",
    r"(^ ^;)": "neutral",
    r"(^.^)": "positive",
    r"(^。^)": "positive",
    r"(^^)": "positive",
    r"(^-^)": "positive",
    r"（＾－＾）": "positive",
    r"(^^)/": "positive",
    r"(^^)v": "positive",
    r"(^^ゞ": "neutral",
    r"(^_-)": "positive",
    r"(^_-)-☆": "positive",
    r"(^_^)": "positive",
    r"(^_^)/": "positive",
    r"(^_^)v": "positive",
    r"(^_^.)": "positive",
    r"(^_^;)": "neutral",
    r"(^_^メ)": "negative",
    r"(^<^)": "positive",
    r"(＾▽＾)": "positive",
    r"（＾◇＾）": "positive",
    r"(^○^)": "positive",
    r"(^・^)": "positive",
    r"(^J^)": "positive",
    r"(^O^)": "positive",
    r"(^o^)": "positive",
    r"(^O^)／": "positive",
    r"(^o^)／": "positive",
    r"(^o^)丿": "positive",
    r"（＾ｕ＾）": "positive",
    r"（＾ｖ＾）": "positive",
    r"(^ム^)": "positive",
    r"('_')": "negative",
    r"(-_-)": "negative",
    r"(゜_゜)": "negative",
    r"(-_-)zzz": "neutral",
    r"(-_-;)": "negative",
    r"(__)": "positive",
    r"(゜_゜>)": "negative",
    r"(_0_)": "neutral",
    r"(-_-メ)": "negative",
    r"(｀´）": "negative",
    r"(~_~)": "negative",
    r"(~_~;)": "negative",
    r"(~_~メ)": "negative",
    r"(~o~)": "negative",
    r"（’-’*)": "positive",
    r"(－－〆)": "negative",
    r"(+_+)": "negative",
    r"(+o+)": "negative",
    r"(=_=)": "negative",
    r"(>_<)": "negative",
    r"(>_<)>": "negative",
    r"(≧∇≦)": "positive",
    r"),:": "negative",
    r"):": "negative",
    r")-:": "negative",
    r")^o^(": "positive",
    r")-=": "negative",
    r")8": "negative",
    r")-8": "negative",
    r")o:": "negative",
    r"*)": "positive",
    r"*-)": "positive",
    r"*\o/*": "positive",
    r":#": "negative",
    r":-#": "negative",
    r":###..": "negative",
    r":-###..": "negative",
    r":$": "negative",
    r":&": "negative",
    r":-&": "negative",
    r":(": "negative",
    r":'(": "negative",
    r":'-(": "negative",
    r":-(": "negative",
    r":-(o)": "negative",
    r":)": "positive",
    r":')": "positive",
    r":'-)": "positive",
    r":-)": "positive",
    r":-))": "positive",
    r":-*": "positive",
    r":*(": "negative",
    r":,(": "negative",
    r":-.": "negative",
    r":[": "negative",
    r":-[": "negative",
    r":^)": "positive",
    r":_(": "negative",
    r":{": "negative",
    r":|": "negative",
    r":-|": "negative",
    r":-||": "negative",
    r":-}": "positive",
    r":} ": "positive",
    r":<": "negative",
    r":-<": "negative",
    r":>": "positive",
    r":->": "positive",
    r":…(": "negative",
    r":0->-<|:": "neutral",
    r":3": "positive",
    r":7": "negative",
    r":-7": "negative",
    r":9": "positive",
    r":b": "positive",
    r":-b": "positive",
    r":b)": "positive",
    r":c": "negative",
    r":-c": "negative",
    r":c) ": "positive",
    r":D": "positive",
    r":-D": "positive",
    r":E": "negative",
    r":F": "negative",
    r":l": "neutral",
    r":O": "negative",
    r":-O": "neutral",
    r":o(": "negative",
    r":o)": "positive",
    r":P": "positive",
    r":p": "positive",
    r":-P": "positive",
    r":-p": "positive",
    r":Q": "negative",
    r":q": "negative",
    r":-Q": "negative",
    r":S": "negative",
    r":s": "negative",
    r":-S": "negative",
    r":Þ": "positive",
    r":-Þ": "positive",
    r":X": "negative",
    r":-X": "negative",
    r";)": "neutral",
    r";-)": "positive",
    r";]": "positive",
    r";-]": "positive",
    r";^)": "positive",
    r";D": "positive",
    r";o)": "neutral",
    r"?_?": "negative",
    r"@.@": "negative",
    r"@_@": "negative",
    r"@}->--": "positive",
    r"＼(^o^)／": "positive",
    r"＼(~o~)／": "positive",
    r"＼(◎o◎)／！": "negative",
    r"＼(-o-)／": "positive",
    r"^/^": "positive",
    r"--^--@": "positive",
    r"^^": "positive",
    r"^^;": "neutral",
    r"^_^": "positive",
    r"^_^;": "neutral",
    r"^5": "positive",
    r"^o)": "negative",
    r"_(._.)_": "positive",
    r"_(_^_)_": "positive",
    r"__|__": "negative",
    r"|;-)": "positive",
    r"|8C": "negative",
    r"|8c": "negative",
    r"|D": "positive",
    r"|-O": "positive",
    r"}:)": "neutral",
    r"}:-)": "neutral",
    r"<(_ _)>": "positive",
    r"<.<": "negative",
    r"</3": "negative",
    r"</3": "negative",
    r"<:-|": "negative",
    r"<:}": "neutral",
    r"<^!^>": "positive",
    r"<`～´>": "negative",
    r"<`ヘ´>": "negative",
    r"<3": "positive",
    r"<m(__)m>": "positive",
    r"<o<": "negative",
    r"=&": "negative",
    r"=-&": "negative",
    r"=(": "negative",
    r"='(": "negative",
    r"=-(": "negative",
    r"=)": "positive",
    r"=')": "positive",
    r"=-)": "positive",
    r"=/": "negative",
    r"=[": "negative",
    r"='[": "negative",
    r"=-[": "negative",
    r"=]": "positive",
    r"=-]": "positive",
    r"={": "negative",
    r"='{": "negative",
    r"=-{": "negative",
    r"=}": "positive",
    r"=-}": "positive",
    r"=<": "negative",
    r"='<": "negative",
    r"=-<": "negative",
    r"=>": "positive",
    r"=->": "positive",
    r"=0": "negative",
    r"=-0": "negative",
    r"=3": "positive",
    r"=-3": "positive",
    r"=7": "negative",
    r"=-7": "negative",
    r"=D": "positive",
    r"=d": "positive",
    r"=-d": "positive",
    r"=-D": "positive",
    r"=o": "negative",
    r"=O": "negative",
    r"=-o": "negative",
    r"=-O": "negative",
    r"=p": "positive",
    r"=P": "positive",
    r"=-P": "positive",
    r"=-p": "positive",
    r"=Q": "negative",
    r"=q": "negative",
    r"=-Q": "negative",
    r"=-q": "negative",
    r">.<": "negative",
    r">.>": "negative",
    r">/": "negative",
    r">:(": "negative",
    r">:)": "positive",
    r">:-)": "positive",
    r">:[": "negative",
    r">:] ": "positive",
    r">:D": "positive",
    r">:L": "negative",
    r">:O": "negative",
    r">:o": "negative",
    r">:P": "positive",
    r">:X": "negative",
    r">;)": "negative",
    r">;]": "positive",
    r">[": "negative",
    r">^_^<": "positive",
    r">_>^ ^<_": "positive",
    r">+(": "negative",
    r">+-(": "negative",
    r">+)": "positive",
    r">+-)": "positive",
    r">+0": "negative",
    r">+-0": "negative",
    r">+O": "negative",
    r">+o": "negative",
    r">+-o": "negative",
    r">+-O": "negative",
    r">=@": "negative",
    r">=D": "negative",
    r">=-D": "negative",
    r">=X": "negative",
    r">o>": "negative",
    r"∩( ・ω・)∩": "positive",
    r"§^。^§": "positive",
    r"°o°": "negative",
    r"°O°": "negative",
    r"0.0": "negative",
    r"0.o": "negative",
    r"0.x": "negative",
    r"0.X": "negative",
    r"0:)": "positive",
    r"0:-3": "positive",
    r"0;^": "positive",
    r"0_X": "negative",
    r"0_x": "negative",
    r"0o": "negative",
    r"0O": "negative",
    r"0-x": "negative",
    r"0-X": "negative",
    r"38*": "negative",
    r"8(": "negative",
    r"8-(": "negative",
    r"8)": "positive",
    r"8-)": "positive",
    r"8/": "negative",
    r"8-0": "negative",
    r"8c": "negative",
    r"8D": "positive",
    r"8-D": "positive",
    r"8-o": "negative",
    r"8-O": "negative",
    r"B(": "negative",
    r"Bc": "negative",
    r"D:": "negative",
    r"D-':": "negative",
    r"D:<": "negative",
    r"D;": "negative",
    r"D=": "negative",
    r"D8": "negative",
    r"DX": "negative",
    r"m(_ _)m": "positive",
    r"m(__)m": "positive",
    r"n_n": "positive",
    r"N_N": "positive",
    r"nn": "positive",
    r"o.0": "negative",
    r"o.O": "negative",
    r"O.o": "negative",
    r"o.X": "negative",
    r"o.x": "negative",
    r"O.x": "negative",
    r"O.X": "negative",
    r"o/\o": "positive",
    r"O:)": "positive",
    r"O:-)": "positive",
    r"o_0": "negative",
    r"o_O": "negative",
    r"O_o": "negative",
    r"o_x": "negative",
    r"O_x": "negative",
    r"o_X": "negative",
    r"O_X": "negative",
    r"o0": "negative",
    r"O0": "negative",
    r"oO": "negative",
    r"Oo": "negative",
    r"o-x": "negative",
    r"o-X": "negative",
    r"O-x": "negative",
    r"O-X": "negative",
    r"Q_Q": "negative",
    r"q_q": "negative",
    r"QQ": "negative",
    r"qq": "negative",
    r"v.v": "negative",
    r"x(": "negative",
    r"X(": "negative",
    r"X-(": "negative",
    r"x.0": "negative",
    r"X.0": "negative",
    r"X.o": "negative",
    r"x.o": "negative",
    r"x.O": "negative",
    r"X.O": "negative",
    r"X_0": "negative",
    r"x_0": "negative",
    r"x_o": "negative",
    r"x_O": "negative",
    r"X_o": "negative",
    r"X_O": "negative",
    r"x0": "negative",
    r"X0": "negative",
    r"x-0": "negative",
    r"X-0": "negative",
    r"X3": "positive",
    r"x3": "positive",
    r"X-3": "negative",
    r"x-3": "negative",
    r"x3?": "positive",
    r"XD": "positive",
    r"xD": "positive",
    r"xd": "positive",
    r"Xd": "positive",
    r"XO": "negative",
    r"Xo": "negative",
    r"xo": "negative",
    r"xO": "negative",
    r"x-o": "negative",
    r"X-o": "negative",
    r"x-O": "negative",
    r"X-O": "negative",
    r"XP": "positive",
    r"xp": "positive",
    r"xP": "positive",
    r"Xp": "positive",
    r"X-P": "positive",
    r"x-p": "positive",
    r"x-P": "positive",
    r"X-p": "positive",
    r"ヽ(^。^)ノ": "positive",
    r"ヽ(^o^)丿": "positive",
    r"-_-": "negative",
    r"-_-*": "negative",
    r"-_-'": "negative",
}
